name: on_toast_widget
description: Flutter Package used to show a custom and animated toast or snackbar Widget.
version: 1.1.0
homepage: https://github.com/LucJosin/on_toast_widget
# pub.dev: https://pub.dev/packages/on_toast_widget
# ========
# author: Lucas Josino
# github: https://github.com/LucJosin
# website: https://www.lucasjosino.com/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
